apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xt5czdahd-nodejs
  janus-idp.io/tekton: xt5czdahd-nodejs
  backstage.io/kubernetes-id: xt5czdahd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xt5czdahd-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
